### ISSUE TITLE
Error report for keycombiner 0.3.0

### ISSUE THREAD

**Issue by HortonsHelpers** [tkainrad/keycombiner#27] opened 2021-08-18 20:30 UTC
Error:
```Error: New version 0.3.2 is not signed by the application owner: publisherNames: Developer ID Application: Thomas Kainrad (YXNM6Q6X29), raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Developer ID Certification Authority",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1782672082000)/",
    "NotBefore": "/Date(1624819283000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "31F570930BFC0DF7",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "938D4254A86CF2514CEFB9EEA03F1ACB695CE177",
    "Version": 3,
    "Issuer": "C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Developer ID Certification Authority",
    "Subject": "C=US, O=Thomas Kainrad, OU=YXNM6Q6X29, CN=Developer ID Application: Thomas Kainrad (YXNM6Q6X29), OID.0.9.2342.19200300.100.1.1=YXNM6Q6X29"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1925424000000)/",
    "NotBefore": "/Date(1609459200000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "0D424AE0BE3A88FF604021CE1400F0DD",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3",
    "Version": 3,
    "Handle": 1866151402048,
    "Issuer": "CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp 2021, O=\"DigiCert, Inc.\", C=US"
  },
  "Status": 1,
  "StatusMessage": "A certificate chain could not be built to a trusted root authority"
}
    at newError (C:\Users\horto\AppData\Local\Programs\keycombiner\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at Object.task (C:\Users\horto\AppData\Local\Programs\keycombiner\resources\app.asar\node_modules\electron-updater\src\NsisUpdater.ts:41:17)
    at NsisUpdater.executeDownload (C:\Users\horto\AppData\Local\Programs\keycombiner\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:617:7)
```
OS: Windows NT 10.0.19043

**Comment by tkainrad** [comment] 2021-08-19 09:35
Hi, thank you for submitting this report. Fortunately, the problem is already fixed in current version 0.3.2.

Please manually remove our current version and install 0.3.2.

See #26 for more details.

**Closed by tkainrad** 2021-08-19 09:35 UTC
