### ISSUE TITLE
Obsidian not recognized as the active application

### ISSUE THREAD

**Issue by sometxdude** [tkainrad/keycombiner#21] opened 2021-06-28 00:26 UTC
I am using the KeyCombiner desktop app on Linux Mint.  I have Obsidian v0.12.5 installed.
When I press Cmd+Alt+C to bring up the lookup it does not recognize Obsidian as the active app.
However, it does work as expected for Chrome and IntelliJ .  

To Reproduce:
1) Open Obsidian on Linux Mint
2) With Obsidian as the active window, press Cmd+Alt+C
3) Lookup window appears, but does not recognize Obsidian as Active.  

IntelliJ and Chrome (the only 2 other apps I tested) are both recognized by KeyCombiner when active.

**Comment by tkainrad** [comment] 2021-06-28 05:59
Hi, thank you for this bug report!

The instant lookup should definitely support Obsidian. In fact, it was one of the first apps I tested with when implementing the instant lookup initially.
It works for me on Ubuntu with the most recent Obsidian AppImage. Fortunately, there should be an easy way to find out why it is not working for you.

Please try to trigger the instant lookup for Obsidian and then post the last couple of lines of your KeyCombiner log file. This is how it looks like for me:

```log
[2021-06-28 07:34:47.890] [info] obsidian
[2021-06-28 07:34:47.890] [info] Found matching collection: obsidian
[2021-06-28 07:34:47.891] [info] will try to load file: /tmp/.mount_KeyComlEwOpo/resources/static/lookup/obsidian.yaml
```

The first line is the application name that KeyCombiner detects. I suspect this is different for you somehow. If I know which name is detected, I can add it as an Obsidian synonym. Good timing also, because the next KeyCombiner Desktop release is due in the upcoming days.

**Comment by sometxdude** [comment] 2021-06-28 13:59
**[2021-06-28 08:26:24.162] [info] No active window found**
**[2021-06-28 08:26:31.863] [info] No active window found**
[2021-06-28 08:27:00.149] [info] Google-chrome
[2021-06-28 08:27:00.150] [info] Found matching collection: chrome
[2021-06-28 08:27:00.150] [info] will try to load file: /tmp/.mount_KeyComlBaI5j/resources/static/lookup/chrome.yaml

The top 2 lines are my attempts when Obsidian is active.  It seems it just doesn't pick up an active window at all.

It turns out this is not an Obsidian-specific issue.  I did some experimentation and the problem occurs with any Flatpak app installed on Linux Mint.  I installed numerous apps from Flatpack and they all show 'No active window found' when invoking the Lookup.  

It seems flatpak itself might be the problem.  When I run the command below, I just see '?' for active.

**flatpak ps --columns=application,active**
Application                   Active
com.github.junrrein.PDFSlicer ?
org.gpodder.gpodder           ?
md.obsidian.Obsidian          ?



All other non-Flatpak apps work properly, or at least the active window is picked up.

**Comment by tkainrad** [comment] 2021-06-28 20:50
Thanks a lot for this additional information. It surprises me that Flatpak leads to problems. 

It is a known limitation that KeyCombiner cannot detect native Wayland windows. However, I didn't know that there are problems with Flatpack apps.

KeyCombiner uses a library which in turn uses `xprop` to find the current application name. You could try to run the `xprop` tool yourself and see what it reports. I guess it will also fail.

Hopefully, I can reproduce the issue eventually and inspect a bit further. I already have ideas how to support Wayland with Gnome. There might be workarounds for your case, too. In the meantime, you could add the Obsidian shortcuts to a personal collection. This way, they will also be included in the instant lookup.

**Comment by tkainrad** [comment] 2021-06-29 13:42
Good News!

I could reproduce your problem on Ubuntu by installing the Flatpak version of Obsidian. From there, it was rather simple to find the cause. The [library that KeyCombiner uses to get the active window](https://github.com/sindresorhus/active-win) tries to also retrieve the installation path to the executable of the active window. This is not possible for Flatpak apps and leads to an error and entirely empty result.

Fortunately, KeyCombiner does not care about the active application's file path. Retrieving the active window's application name is also possible for Flatpak apps. I will submit a fix for this to active-win, so that the application name can be retrieved even if it is not possible to read the installation path. Once it is fixed there, I will release a new KeyCombiner version.

Altogether, the problem should be solved within a couple of weeks. Thank you very much for reporting this!

**Comment by sometxdude** [comment] 2021-06-29 14:36
You're welcome.  That all makes perfect sense. This is a very minor issue for me as Obsidian is the only Flatpak app I would probably use with keyboard shortcuts and I do have the personal shortcuts set up as a fallback.  Good job on KeyCombiner!

**Comment by tkainrad** [comment] 2021-07-01 19:01
[This is now fixed in active-win](https://github.com/sindresorhus/active-win/pull/119) and will be fixed in KeyCombiner with its July release due in a couple of weeks. All Flatpak applications should work then.

**Closed by tkainrad** 2021-07-01 19:01 UTC
Labels: bug
